import React, { useEffect, useMemo, useState } from "react";
import BlogCard from './components/BlogCard';
import { Link } from 'react-router-dom';
import Overall from './images/Overall.jpg';

const BlogList = () => {
  const blogs = [
    {
      title: 'Filament Recycler Under 100 Dollars',
      description: 'An Open Source solution to the waste generated by your printer',
      date: 'Oct 16, 2024',
      preview: '3D printing enthusiasts often face the issue of filament waste, which not only impacts the environment but also adds ...',
      imageUrl: Overall,
      url: 'Filament-Recycler'
    },
  ];

  return (
    <div style={{ position: "relative", height: "100vh" }}>
      
        <div style={{
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'center',
          gap: '2.5em',
          padding: '2em',
          zIndex: 1,
          position: 'relative',
          alignContent: 'flex-start',
        }}>
          <h1 style={{ 
            width: '100%',
            textAlign: 'center', 
            fontSize: '2.5em', 
            marginBottom: '1.5em', 
            color: '#333',
            marginTop: '1em'
          }}>
            Our Blogs
          </h1>
          {blogs.map((blog, index) => (
            <Link to={`/blogs/${blog.url}`} key={index}>
              <BlogCard
                title={blog.title}
                description={blog.description}
                date={blog.date}
                preview={blog.preview}
                imageUrl={blog.imageUrl}
              />
            </Link>
          ))}
        </div>
      </div>  
  );
};

export default BlogList;
