import HeroSection from "./components/heroSection";
import LatestProduct from "./components/product";
import LatestCard from "./components/latestSection"
import { Link } from 'react-router-dom';
import latestImg from './components/images/spooler.png'

const HomePage = () => {
  return (
    <main className="min-h-screen pt-[48px]">
      <section className="flex flex-col lg:flex-row">
      <div className="flex justify-center items-center">
        <HeroSection />
      </div>
      <div className="flex justify-center items-center ">
        <LatestProduct />
      </div>
    </section>

      <Link to={"/blogs"}>
      <LatestCard title="Check out our Latest Blog!"
                  description="An open source project that recycles filament waste generated by 3d printers back into reusable filament"
                  date='15th October'
                  imageUrl={latestImg}
      />  
      </Link>
    </main>
  );
};

export default HomePage;
